### PR TITLE
add css art

### PR DESCRIPTION
**Pull request by adetoye-dev**
# Hi 😊
This is a PR template. It is used to make things nice and simple for both Participants and Maintainers of this challenge.
<br>
Please fill out the required fields listed below:

## <ins> Participant's checklist </ins>

<small>  To mark a field complete, add an 'x' between the square brackets below like this '[x]'</small>

- [x] I have made sure my submission is not breaking other people's content
- [x] I have made sure my submission is responsive across all devices (minimum width 280px)
- [x] I have made sure to resolve any merge conflicts
- [x] I have used appropriate HTML5 elements
- [x] I have added myself as the assignee on this PR

## <ins>  Maintainer's checklist </ins>

- Check if the assignee and the reviewer have been tagged
- Check if the submission is breaking any listed rules
- Check if the submission has any merge conflicts 
- Test the code locally to make sure nothing is broken
- Check all content submitted is responsive across all devices (minimum width 280px)
- Update the Participant on the status of their PR via comments

### Thank you for your time 💛

### CODE REVIEW

**Comment by mateahoward** [comment]
Hiya @adetoye-dev 😄 Thank you for your contribution, I'm gonna take a look at it and update you with the status after the review 😄

**Comment by mateahoward** [comment]
I've now taken a look and your house looks beautiful 🎖️ We do seem to have a minor issue on mobile view where your card becomes a little bit too wide and adds a horizontal scroll at around 322px width and below. Would you mind taking a look and making sure it looks okay until we reach 280px in width so that it continues to look just as lovely on smaller screens, please? 👍

**Comment by adetoye-dev** [comment]
> I've now taken a look and your house looks beautiful 🎖️ We do seem to have a minor issue on mobile view where your card becomes a little bit too wide and adds a horizontal scroll at around 322px width and below. Would you mind taking a look and making sure it looks okay until we reach 280px in width so that it continues to look just as lovely on smaller screens, please? 👍

Sure, I'll work on that 😇👍

**Comment by mateahoward** [comment]
Thank you very much 😄

**Comment by mateahoward** [comment]
Hiya @adetoye-dev, we have just merged another PR while waiting for your change. 
You might want to resolve conflicts before your next update 😄

**Comment by adetoye-dev** [comment]
> Hiya @adetoye-dev, we have just merged another PR while waiting for your change. You might want to resolve conflicts before your next update 😄

Alright 😅

**Comment by adetoye-dev** [comment]
Hi, I have fixed the overflow issue with responsiveness and resolved the conflict

**Comment by adetoye-dev** [comment]
Is it okay to close this pr and reopen with the changes I made??

**Comment by adetoye-dev** [comment]
This pr has a conflict and is also not responsive on screen size of 280 so I would create a new pr with the changes  I made

**Pull request closed without merging**
